name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter pillow pyinstaller

      - name: Build EXE
        run: |
          python -m PyInstaller --noconfirm --clean --onefile --windowed --name "ParaMiPeanut" --add-data "assets;assets" --collect-all customtkinter main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ParaMiPeanut-Windows
          path: dist/ParaMiPeanut.exe
